CREATE TABLE IF NOT EXISTS networks (id TEXT PRIMARY KEY, name TEXT NOT NULL, cidr CIDR NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS subnets (id TEXT PRIMARY KEY, network_id TEXT NOT NULL REFERENCES networks(id), cidr CIDR NOT NULL);
CREATE TABLE IF NOT EXISTS pools (id TEXT PRIMARY KEY, subnet_id TEXT NOT NULL REFERENCES subnets(id), start_ip INET NOT NULL, end_ip INET NOT NULL);
CREATE TABLE IF NOT EXISTS leases (id TEXT PRIMARY KEY, pool_id TEXT NOT NULL REFERENCES pools(id), client_id TEXT NOT NULL, address INET NOT NULL, family TEXT NOT NULL, state TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, version BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS conflicts (id TEXT PRIMARY KEY, address INET NOT NULL, reason TEXT NOT NULL, detected_at TIMESTAMPTZ NOT NULL, resolved BOOLEAN NOT NULL DEFAULT FALSE);
